import React from 'react';
// En testData.js
export const testData = [
  { name: "Juan", index: 1, ranking: 1, fotos: 5, avatarUrl: "https://randomuser.me/api/portraits/lego/1.jpg" },
  { name: "Maria", index: 2, ranking: 2, fotos: 8, avatarUrl: "https://randomuser.me/api/portraits/women/2.jpg" },
  { name: "Carlos", index: 3, ranking: 3, fotos: 12, avatarUrl: "https://randomuser.me/api/portraits/lego/3.jpg" },
  { name: "Ana", index: 4, ranking: 4, fotos: 15, avatarUrl: "https://randomuser.me/api/portraits/women/4.jpg" },
  { name: "David", index: 5, ranking: 5, fotos: 10, avatarUrl: "https://randomuser.me/api/portraits/lego/5.jpg" },
];

export const testData1 = [
  { photo: "Luz Clara", name: "Moogly", index: 0, likes: 145, favorites: 34, photoUrl: "https://picsum.photos/id/200/800/900" },
  { photo: "Espejismo", name: "Luke", index: 1, likes: 166, favorites: 43, photoUrl: "https://picsum.photos/id/201/800/900" },
  { photo: "Belleza Americana", name: "Simba", index: 2, likes: 187, favorites: 25, photoUrl: "https://picsum.photos/id/202/800/900" },
  { photo: "Serenidad Azul", name: "Mickey", index: 3, likes: 206, favorites: 47, photoUrl: "https://picsum.photos/id/203/800/900" },
  { photo: "Amanecer Dorado", name: "Donald", index: 4, likes: 217, favorites: 32, photoUrl: "https://picsum.photos/id/204/800/900" },
  { photo: "Atardecer Anaranjado", name: "Ariel", index: 5, likes: 228, favorites: 38, photoUrl: "https://picsum.photos/id/10/800/900" },
  { photo: "Jardín Secreto", name: "Batman", index: 6, likes: 525, favorites: 21, photoUrl: "https://picsum.photos/id/206/800/900" },
  { photo: "Viento Fresco", name: "Superman", index: 7, likes: 857, favorites: 29, photoUrl: "https://picsum.photos/id/11/800/900" },
  { photo: "Cielo Estrellado", name: "Spiderman", index: 8, likes: 332, favorites: 41, photoUrl: "https://picsum.photos/id/208/800/900" },
  { photo: "Montaña Nevada", name: "Wolverine", index: 9, likes: 390, favorites: 36, photoUrl: "https://picsum.photos/id/209/800/900" },
  { photo: "Olas Bravas", name: "Darth Vader", index: 10, likes: 407, favorites: 45, photoUrl: "https://picsum.photos/id/210/800/900" },
  { photo: "Aurora Boreal", name: "Yoda", index: 11, likes: 666, favorites: 27, photoUrl: "https://picsum.photos/id/211/800/900" },
  { photo: "Primavera", name: "Hulk", index: 12, likes: 34, favorites: 37, photoUrl: "https://picsum.photos/id/212/800/900" },
  { photo: "Invierno", name: "Iron Man", index: 13, likes: 6, favorites: 49, photoUrl: "https://picsum.photos/id/213/800/900" },
  { photo: "Otoño", name: "Thor", index: 14, likes: 778, favorites: 28, photoUrl: "https://picsum.photos/id/214/800/900" },
  { photo: "Verano", name: "Captain America", index: 15, likes: 1419, favorites: 33, photoUrl: "https://picsum.photos/id/215/800/900" },
  { photo: "Estrella", name: "Wonder Woman", index: 16, likes: 2293, favorites: 46, photoUrl: "https://picsum.photos/id/216/800/900" },
  { photo: "Mar", name: "Black Widow", index: 17, likes: 1156, favorites: 22, photoUrl: "https://picsum.photos/id/217/800/900" },
  { photo: "Montaña", name: "Hermione", index: 18, likes: 411, favorites: 31, photoUrl: "https://picsum.photos/id/218/800/900" },
  { photo: "Río", name: "Harry Potter", index: 19, likes: 382, favorites: 42, photoUrl: "https://picsum.photos/id/219/800/900" },
  { photo: "Lago", name: "Moogly", index: 20, likes: 137, favorites: 40, photoUrl: "https://picsum.photos/id/220/800/900" },
  { photo: "Nube", name: "Luke", index: 21, likes: 276, favorites: 35, photoUrl: "https://picsum.photos/id/221/800/900" },
  { photo: "Arco Iris", name: "Simba", index: 22, likes: 192, favorites: 24, photoUrl: "https://picsum.photos/id/222/800/900" },
  { photo: "Universo", name: "Mickey", index: 23, likes: 394, favorites: 48, photoUrl: "https://picsum.photos/id/223/800/900" },
  { photo: "Luz Clara", name: "Donald", index: 24, likes: 227, favorites: 39, photoUrl: "https://picsum.photos/id/14/800/900" },
  { photo: "Espejismo", name: "Ariel", index: 25, likes: 158, favorites: 23, photoUrl: "https://picsum.photos/id/225/800/900" },
  { photo: "Belleza Americana", name: "Batman", index: 26, likes: 308, favorites: 44, photoUrl: "https://picsum.photos/id/16/800/900" },
  { photo: "Serenidad Azul", name: "Superman", index: 27, likes: 176, favorites: 26, photoUrl: "https://picsum.photos/id/227/800/900" },
  { photo: "Amanecer Dorado", name: "Spiderman", index: 28, likes: 341, favorites: 30, photoUrl: "https://picsum.photos/id/228/800/900" },
  { photo: "Atardecer Anaranjado", name: "Wolverine", index: 29, likes: 205, favorites: 50, photoUrl: "https://picsum.photos/id/229/800/900" },
  { photo: "Jardín Secreto", name: "Darth Vader", index: 30, likes: 382, favorites: 37, photoUrl: "https://picsum.photos/id/230/800/900" },
  { photo: "Viento Fresco", name: "Yoda", index: 31, likes: 145, favorites: 45, photoUrl: "https://picsum.photos/id/231/800/900" },
  { photo: "Cielo Estrellado", name: "Hulk", index: 32, likes: 289, favorites: 33, photoUrl: "https://picsum.photos/id/232/800/900" },
  { photo: "Montaña Nevada", name: "Iron Man", index: 33, likes: 209, favorites: 21, photoUrl: "https://picsum.photos/id/233/800/900" },
  { photo: "Olas Bravas", name: "Thor", index: 34, likes: 397, favorites: 48, photoUrl: "https://picsum.photos/id/234/800/900" },
  { photo: "Aurora Boreal", name: "Captain America", index: 35, likes: 171, favorites: 22, photoUrl: "https://picsum.photos/id/235/800/900" },
  { photo: "Primavera", name: "Wonder Woman", index: 36, likes: 326, favorites: 39, photoUrl: "https://picsum.photos/id/236/800/900" },
  { photo: "Invierno", name: "Black Widow", index: 37, likes: 190, favorites: 45, photoUrl: "https://picsum.photos/id/237/800/900" },
  { photo: "Otoño", name: "Hermione", index: 38, likes: 253, favorites: 34, photoUrl: "https://picsum.photos/id/238/800/900" },
  { photo: "Verano", name: "Harry Potter", index: 39, likes: 437, favorites: 49, photoUrl: "https://picsum.photos/id/239/800/900" },
  { photo: "Estrella", name: "Moogly", index: 40, likes: 162, favorites: 27, photoUrl: "https://picsum.photos/id/240/800/900" },
  { photo: "Mar", name: "Luke", index: 41, likes: 291, favorites: 46, photoUrl: "https://picsum.photos/id/241/800/900" },
  { photo: "Montaña", name: "Simba", index: 42, likes: 217, favorites: 36, photoUrl: "https://picsum.photos/id/242/800/900" },
  { photo: "Río", name: "Mickey", index: 43, likes: 373, favorites: 47, photoUrl: "https://picsum.photos/id/243/800/900" },
  { photo: "Lago", name: "Donald", index: 44, likes: 128, favorites: 25, photoUrl: "https://picsum.photos/id/244/800/900" },
  { photo: "Nube", name: "Ariel", index: 45, likes: 314, favorites: 35, photoUrl: "https://picsum.photos/id/15/800/900" },
  { photo: "Arco Iris", name: "Batman", index: 46, likes: 178, favorites: 31, photoUrl: "https://picsum.photos/id/17/800/900" },
  { photo: "Universo", name: "Superman", index: 47, likes: 259, favorites: 48, photoUrl: "https://picsum.photos/id/247/800/900" },
  { photo: "Luz Clara", name: "Spiderman", index: 48, likes: 392, favorites: 44, photoUrl: "https://picsum.photos/id/248/800/900" },
  { photo: "Espejismo", name: "Wolverine", index: 49, likes: 843, favorites: 23, photoUrl: "https://picsum.photos/id/249/800/900" }
];


export const testData2 = 
[
  { name: "Libre", index: 1, icon: "fa-pen-fancy", backUrl: "https://picsum.photos/id/520/300/400/?blur=2" },
  { name: "Vida Salvaje", index: 2, icon: "fa-otter", fotos: 8, backUrl: "https://picsum.photos/id/320/300/400/?blur=3" },
  { name: "Urbano", index: 3, icon: "fa-bookmark",  backUrl: "https://picsum.photos/id/352/300/400/?blur=3" },
  { name: "Retrato", index: 4, icon: "fa-camera-retro",  backUrl: "https://picsum.photos/id/244/300/400/?blur=3" },
  { name: "Paisajes", index: 5, icon: "fa-video",  backUrl: "https://picsum.photos/id/243/300/400/?blur=3" },
  { name: "Blanco y Negro", index: 6, icon: "fa-wand-magic-sparkles", backUrl: "https://picsum.photos/id/237/200/300/?blur=3" },
];

export const testData3 =
[
  { name: "acostada", index: 0, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/acostada.jpg" },
  { name: "avatar", index: 1, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/avatar.png" },
  { name: "banner", index: 2, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/banner.png" },
  { name: "board", index: 3, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/board.jpg" },
  { name: "boyPaper", index: 4, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/boyPaper.jpg" },
  { name: "buho", index: 5, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/buho.jpg" },
  { name: "cameraBoy", index: 6, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/cameraBoy.jpg" },
  { name: "cameraGirl", index: 7, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/cameraGirl.jpg" },
  { name: "category", index: 8, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/category.png" },
  { name: "emprende", index: 9, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/emprende.jpg" },
  { name: "loro", index: 10, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/loro.jpg" },
  { name: "ojo", index: 11, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/ojo.jpg" },
  { name: "ojos", index: 12, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/ojos.jpg" },
  { name: "people", index: 13, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/people.jpg" },
  { name: "photographer", index: 14, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/photographer.jpg" },
  { name: "rostro1", index: 15, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/rostro1.jpg" },
  { name: "selfie", index: 16, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/selfie.jpg" },
  { name: "yoni", index: 17, fotoUrl: "https://raw.githubusercontent.com/4GeeksAcademy/final_prueba/main/src/front/img/yoni.png" },
];