"""empty message

Revision ID: 02824501dbdd
Revises: c5d96459ef06
Create Date: 2024-01-23 00:21:48.958131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02824501dbdd'
down_revision = 'c5d96459ef06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite__photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorite_photo_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photo_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('photo_likes_favorite_photo_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'photos', ['photo_id'], ['id'])
        batch_op.drop_column('favorite_photo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('photo_likes_favorite_photo_id_fkey', 'photos', ['favorite_photo_id'], ['id'])
        batch_op.drop_column('photo_id')

    op.drop_table('favorite__photos')
    # ### end Alembic commands ###
