"""empty message

Revision ID: 285c00f4d6ee
Revises: c9e745d0a270
Create Date: 2024-01-31 22:53:01.481972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285c00f4d6ee'
down_revision = 'c9e745d0a270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
