"""empty message

Revision ID: c5d96459ef06
Revises: 3371a4dcdcc7
Create Date: 2024-01-23 00:16:50.569504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d96459ef06'
down_revision = '3371a4dcdcc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorite_photo_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_likes')
    # ### end Alembic commands ###
